version: '3.8'

services:
  run-model-locally:
    container_name: colors_model-local-starter
    restart: "no"
    image: tianon/true
    depends_on:
      - colors_model

  colors_model:
    container_name: colors_model
    build:
      context: .
    command: poetry run python ./colors_model/model.py --name colors_model  --type colors
    image: colors_model:latest
    restart: unless-stopped
    volumes:
      - .:/app-workspace
    env_file:
      - .env
    networks:
      - picachu-api-private_picachu-net

networks:
  picachu-api-private_picachu-net:
    external: true